### ISSUE TITLE
How about the infix space linter has a feature to exclude any infix tokens?

### ISSUE THREAD

**Issue by yu-iskw** [jimhester/lintr#103]
Hi @jimhester, 

I think it would be nice to exclude any infix tokens. For example, `^` is used without infix spaces, i.e. `2^3`.
https://github.com/jimhester/lintr/blob/master/R%2Finfix_spaces_linter.R#L1

For example,

```
infix_spaces_linter(exclude=c("'^'"))
```

**Comment by walmes** [comment]
I'm also interested in this option because I use `^` and `/` without infix spaces. The object that defines the operators is `lintr:::infix_tokens` but it is not exported. If this object was exported, would be enough to reset it with new values. Also, a side effect modification in `spaces_left_parentheses_linter` function to allow `2^(1:4)` and `(2 + 4)/(3 + 6)`, `^/` before `(`, would be nice.

**Comment by MichaelChirico** [comment]
Closing for the same reason as #434 -- I think it is up to downstreams to write custom linters to implement this since it's not tidyverse style (btw a bit unfortunately IMHO!)
