### ISSUE TITLE
lintr not released to CRAN since April 2016

### ISSUE THREAD

**Issue by dfrankow** [jimhester/lintr#230]
Thanks for your work on lintr. Great stuff.

https://cran.r-project.org/web/packages/lintr/index.html shows a release date of 2016-04-16.

https://github.com/jimhester/lintr/issues/228 says https://github.com/jimhester/lintr/issues/127 (fixed Dec 2015!) is "fixed in the development version", i.e. not CRAN.

So, now I have to tell everyone to install from github?

Is it reasonable to tie off another version and send it to CRAN right now? Is this something I could help with? I am ignorant of what that involves, or what state the master branch is in.

**Comment by jimhester** [comment]
That issue was fixed this November of 16, so only a few months old.

In general there wasn't a lot of development on lintr last year, up until a month or so ago. The current master is not currently in a state that could be released, but once we get it into better shape we will have a new CRAN release.
