### ISSUE TITLE
Configuration documentation: ST3

### ISSUE THREAD

**Issue by taqtiqa-mark** [jimhester/lintr#273]
I have the same questions as this user:
https://stackoverflow.com/questions/42880328/configure-the-behaviour-of-r-linters-in-sublime-3

Some more documentation about how to configure lintr in ST3 would be much appreciated.

**Comment by mccurcio** [comment]
@taqtiqa-mark **Hear, hear**
Directions or increased documentation would be appreciated.

**Comment by taqtiqa-mark** [comment]
OK, I'll leave this open.  However, I have switched to VS Code.

**Comment by russHyde** [comment]
@mccurcio do you have a specific question regarding configuration?

There are some notes on sublime text here: https://github.com/jimhester/lintr#sublime-text-3

Settings for lintr are specified in a similar way to other uses of lintr, but you do it in the SublimeLinter User Settings rather than in a .lintr config file.

Adding this code to the User Settings would tell lintr to use all default linters (see lintr::default_linters for the names of the defaults), but to disregard the `assignment_linter` and to replace the default line-length-linter with one that throws when the line-length is > 120.

```
{
  "linters": {
    "lintr": {
      "linters": "with_defaults(assignment_linter = NULL, line_length_linter(120))"
    }
  }
}
```

**Comment by mccurcio** [comment]
Hi Russ,
Thanks for getting back to me. Actually I am using RStudio  not sublime. I
was just looking for some basics. I would like to not check for spaces at
the end of lines or snake case variables. Just some basic commands that is
all.
Thanks

**Comment by taqtiqa-mark** [comment]
Closing since no actual user exists with this issue, and there is now issue #419
