### ISSUE TITLE
Run Lintr through Command Line on R file

### ISSUE THREAD

**Issue by aksh7860** [jimhester/lintr#278]
How can i run lintr through command line on a R file ??

**Comment by jimhester** [comment]
The same way you run any R code from the command line.

```shell
Rscript -e 'lintr::lint(commandArgs(trailingOnly = TRUE))' filename
```

**Comment by aksh7860** [comment]
Thanks for helping out

**Comment by greggles** [comment]
I was curious how to do this as well. Thanks for explaining it.

It could be useful to give some examples like this in the README.md as I looked there first and didn't see how to do it.

**Comment by rahulrachh** [comment]
Another way to run lintr is with following command:
 `Rscript -e "lintr::lint('path/of/the/file')"`

Note:
1) When the expression starts it has `"` double quotes. Don't replace it with `'` single quotes.
2) Also, when the file path argument starts, it has `'` single quote. Don't replace it with `"` double quotes. 
3) As the file path of Windows has `\` , it needs to be replaced with `/` because R doesn't allow `\` .

You can change the place of the `'` and `"` and can see for yourself that the command doesn't work.

**Comment by reposhyammohan** [comment]
Hi  @jimhester  , 
Thanks for this wonderful feature . Is there any total score output by considering all the analysis output ? . If not it would be a nice to have feature .
Regards
Shyam
