### ISSUE TITLE
License

### ISSUE THREAD

**Issue by slmagus** [jimhester/lintr#320]
I know this may be a minor issue to many but our Agency has a fairly strict free software usage policy. At present our organization could not use lintr. It looks like the LICENSE is missing the important MIT stuff, that it used to have. Any chance you could readd the full MIT License text merge back into master? 

https://github.com/jimhester/lintr/commit/5fe7fc0319fbcf05cc82f1777b55b82a8964ea32#diff-9879d6db96fd29134fc802214163b95a

**Comment by dougmet** [comment]
I've a feeling that the short LICENSE file is a CRAN policy https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing and if it's standard MIT then this refers to a copy held in `share/licenses` which is here on my machine `C:\Program Files\R\R-3.4.3\share\licenses` so that's where you get your long text. Is that sufficient?

**Comment by randy3k** [comment]
Ya, it is a cran stuff. Check https://cran.r-project.org/web/packages/lintr/index.html for the complete license statement.

**Comment by slmagus** [comment]
@dougmet I think so. The lawyers really just care that somewhere it says MIT which it does in https://github.com/jimhester/lintr/blob/fe4104a2d1c5c6ae9ad8daa79925c9d11127c142/DESCRIPTION#L33 . Admittedly I a more familiar with LICENSE containing the full license text.  In the end I wasn't sure so I asked. Thanks for the info.

**Comment by jimhester** [comment]
Yeah, I agree it would be easier if the LICENSE file had the full license, but CRAN wants it done this way, see the instructions for the MIT license by CRAN at https://cran.r-project.org/web/licenses/MIT
