### ISSUE TITLE
Feature suggestion: use_lintr_test

### ISSUE THREAD

**Issue by maelle** [jimhester/lintr#340]
I'm adding a `lintr` unit test to a package using the template provided in the README and was wondering whether there could be a `use_lintr_test` function that'd create the test and add `lintr` to DESCRIPTION?

**Comment by maelle** [comment]
Oh I had missed it already exists!! 🤦‍♀️ `use_test("lintr")`

**Comment by jimhester** [comment]
There could be, however I now don't think adding lintr to your test suite is a great idea. These tests take a long time to run (because lintr is fairly slow) and I find adding them to my test suite hinders my development because the tests take longer to run.

I would recommend instead adding lintr as a separate step in your build process in a `before_test:` block.

**Comment by maelle** [comment]
Ah interesting! Then I'll close this and open an issue in `tic` 😸
