### ISSUE TITLE
.lintr file in home dir on Windows not found

### ISSUE THREAD

**Issue by Hong-Revo** [jimhester/lintr#374]
lintr doesn't seem to be able to make use of a .lintr file in my home directory (`c:\users\hongooi\documents\.lintr`). Only if the file is present in my current working directory does it take effect.

Eg I have the following in `c:\users\hongooi\documents\.lintr` to turn off all checks:

```
linters: with_defaults(absolute_paths_linter=NULL,
    assignment_linter=NULL,
    closed_curly_linter=NULL,
    commas_linter=NULL,
    commented_code_linter=NULL,
    infix_spaces_linter=NULL,
    line_length_linter=NULL,
    no_tab_linter=NULL,
    object_usage_linter=NULL,
    camel_case_linter=NULL,
    snake_case_linter=NULL,
    multiple_dots_linter=NULL,
    object_length_linter=NULL,
    open_curly_linter=NULL,
    single_quotes_linter=NULL,
    spaces_inside_linter=NULL,
    spaces_left_parentheses_linter=NULL,
    trailing_blank_lines_linter=NULL,
    trailing_whitespace_linter=NULL)
```

But if I run `lint_package()` in a different directory (where I'm developing a package), I still get various warnings. The warnings only disappear after I copy the file into the package directory.

**Comment by Hong-Revo** [comment]
Nevermind, I didn't realise that there is no option for a global lintr config.

**Comment by eddelbuettel** [comment]
@Hong-Revo -- there is now!  And this post of yours just saved me as there is apparently no documentation whatsoever in the package itself about a config file (format) apart from a hint that a global file is read.  I used your block above, and added one line to suppress the (shall we say also controversial) call to the `object_name_linter` with its `snake_name` default.

Now ESS may be usable again again after the more recent version, paired with the 2.0.0 release on CRAN, suddenly turns this on.  (That ESS does that automagically is another story....)

```sh
edd@rob:~$ cat ~/.lintr 
linters: with_defaults(absolute_paths_linter=NULL,
    assignment_linter=NULL,
    closed_curly_linter=NULL,
    commas_linter=NULL,
    commented_code_linter=NULL,
    infix_spaces_linter=NULL,
    line_length_linter=NULL,
    no_tab_linter=NULL,
    object_usage_linter=NULL,
    camel_case_linter=NULL,
    snake_case_linter=NULL,
    multiple_dots_linter=NULL,
    object_name_linter=NULL,
    object_length_linter=NULL,
    open_curly_linter=NULL,
    single_quotes_linter=NULL,
    spaces_inside_linter=NULL,
    spaces_left_parentheses_linter=NULL,
    trailing_blank_lines_linter=NULL,
    trailing_whitespace_linter=NULL)
edd@rob:~$ 
```

**Comment by russHyde** [comment]
@eddelbuettel  . If you are using lintr 2.0.0, then `camel_case_linter`, `snake_case_linter`, `multiple_dots_linter` are no longer part of the `default_linters`; so you needn't NULL them out.

**Comment by eddelbuettel** [comment]
@russHyde I am all ears but that is _the exact opposite_ of what I am seeing with everything current to CRAN, including `lintr`.  And before posting I did three things:
- validate that without `~/.lintr` I indeed get pages full for a moderately-sized .R file of mine on CRAN
- with Hong's file I get less but still 'snake' warnings
- adding it I get none:

```sh
edd@rob:~/git/anytime(master)$ r -llintr -p -e'lint("R/anytime.R")'
edd@rob:~/git/anytime(master)$ grep snake ~/.lintr
    snake_case_linter=NULL,
edd@rob:~/git/anytime(master)$ 
edd@rob:~/git/anytime(master)$ mv ~/.lintr ~/.lintr.hidden
edd@rob:~/git/anytime(master)$ r -llintr -p -e'lint("R/anytime.R")' | wc -l
294
edd@rob:~/git/anytime(master)$ 
```

That seems to be in conflict with your statement.  (I didn't bother re-running with/without the snake line but I could.)   How can we square this?  Shall we cook up a [MCVE](https://stackoverflow.com/help/mcve) somewhere?

**Comment by russHyde** [comment]
From what I understood, you also introduced `object_name_linter = NULL` to Hong's `.lintr` file. 

In lintr 2, it is by suppressing `object_name_linter` in `with_defaults(...)` that you've prevented a snake-case linter from running. `lint(..., with_defaults(..., snake_case_linter = NULL, ...))` shouldn't modify the default linter list anymore, since `snake_case_linter` is no longer one of the `default_linters`.

~~~~
names(default_linters)
 [1] "assignment_linter"                "closed_curly_linter"             
 [3] "commas_linter"                    "commented_code_linter"           
 [5] "cyclocomp_linter"                 "equals_na_linter"                
 [7] "function_left_parentheses_linter" "infix_spaces_linter"             
 [9] "line_length_linter"               "no_tab_linter"                   
[11] "object_length_linter"             "object_name_linter"              
[13] "object_usage_linter"              "open_curly_linter"               
[15] "paren_brace_linter"               "pipe_continuation_linter"        
[17] "seq_linter"                       "single_quotes_linter"            
[19] "spaces_inside_linter"             "spaces_left_parentheses_linter"  
[21] "trailing_blank_lines_linter"      "trailing_whitespace_linter"
~~~~

Apologies if I've took this thread away from the issue of global .lintr accessibility.

**Comment by eddelbuettel** [comment]
Ok, maybe you can help me out here if I am still doing it wrong:
- without me opting in, my default environment is now checking ALL files related to R
- the checks are too aggressive
- I want to turn them off
     - first all
     - later possibly turning them off

There was no documentation in the package or its vignettes to help me.  I found this ticket, and got my issue solved.  Good.  So far.

Now you (possibly quite correctly) point out "I am doing it wrong". You are likely right.  How do you suggest I go about my usual work with the least amount of fuzz and bother given the requirements above?   And please talk to me like I am a five-year old I neither use `lintr` (so far) nor am steeply versed in some other conventions of some other people.  I just use R and write some packages.

**Comment by russHyde** [comment]
No problem.
The only difference I was suggesting was that you use the following as your .lintr to achieve the same goal. Your original version included several linters that aren't part of the default linter list in the version of lintr that you are using.

```
linters: with_defaults(absolute_paths_linter=NULL,
    assignment_linter=NULL,
    closed_curly_linter=NULL,
    commas_linter=NULL,
    commented_code_linter=NULL,
    infix_spaces_linter=NULL,
    line_length_linter=NULL,
    no_tab_linter=NULL,
    object_usage_linter=NULL,
    object_name_linter=NULL,
    object_length_linter=NULL,
    open_curly_linter=NULL,
    single_quotes_linter=NULL,
    spaces_inside_linter=NULL,
    spaces_left_parentheses_linter=NULL,
    trailing_blank_lines_linter=NULL,
    trailing_whitespace_linter=NULL)
```

Note that the lines for `camel_case_linter`, `snake_case_linter` and `multiple_dots_linter` have been removed.
This doesn't actually alter the set of linters that will be applied to your files.
`lintr::with_defaults()` is being used to define the linting functions that are active.

If you provide no arguments to `with_defaults()`, it will use all of the named linters that are present in the list `lintr::default_linters`.

If you provide a named argument with a NULL value, eg `with_defaults(object_name_linter = NULL)` and the name of the argument is present in `default_linters`, then that named linter will be turned off (so, here that turns off the `object_name_linter`)

If you provide a named argument with a linting function as its value, eg, `with_defaults(object_name_linter = object_name_linter(c("CamelCase", "dotted.case")))` then that linting function will be included in the set of linters that are used during your run of `lint`. Here, that means that all newly defined objects should have a name that is either CamelCase or dotted.case.

[aside: For this example, since `object_name_linter` is a name of one of the default linters (and by default only allows `snake_case` objects), we actually replace the object-name linting function in the set of default linters with an alternative object-name linting function]

If you are using `with_defaults` to deselect from the default linters; eg using `with_defaults(camel_case_linter = NULL)`, those linters will only be deselected if they correspond to the name of a linter within the list `default_linters`. Here, since `camel_case_linter` is not present in `default_linters`, using `with_defaults(camel_case_linter = NULL)` has no effect, because `camel_case_linter` wouldn't have been included in active linters anyway.


This has been very helpful. Will open an issue to expand the documentation re the config section (https://github.com/jimhester/lintr#project-configuration).

**Comment by eddelbuettel** [comment]
Awesome. Was thinking about suggesting the same while still reading it -- this would IMHO help the package.

(Personally, I also like global config getters that just print.  Assume people new to the package know nothing,...)
