### ISSUE TITLE
Add a linter to check that arguments after '...' start with a dot

### ISSUE THREAD

**Issue by paulponcet** [jimhester/lintr#449]
It seems good practice to have function arguments starting with a `.` when they are placed after `...`.

    # Bad
    function(x, y, ..., verbose = TRUE) {
      # some code
    }

    # Good
    function(x, y, ..., .verbose = TRUE) {
      # some code
    }

**Comment by russHyde** [comment]
Thanks. Is this a common practice, I haven't seen this in use much. Is it included in one of the established style guides (google / tidyverse / bioconductor)?

**Comment by MichaelChirico** [comment]
This isn't in any style guide I know of; and in particular we hew to the Tidyverse guide, which doesn't have it:

https://style.tidyverse.org/functions.html

Therefore you would have to implement this as a custom linter; please check the [vignette](https://cran.r-project.org/web/packages/lintr/vignettes/creating_linters.html)

PS please feel free to add any feedback about that vignette to #610 since we plan some overhaul to that vignette already
