### ISSUE TITLE
RStudio: no more linters, pane "Markers" stays 

### ISSUE THREAD

**Issue by razz-matazz** [jimhester/lintr#520]
Hello,

When lintering a file in RStudio, a pane "Markers" opens and displays the linters. Fine.
When lintering the file again, the pane refreshes. As long as linters are found. If not, the pane doesn't refresh (or close).

RStudio version 1.3.1056, Windows 10.

**Comment by AshesITR** [comment]
Thanks for reporting this. I've looked into it and confirmed the problem:
The issue is with the conditional `if (length(x))` in `print.lints`.

https://github.com/jimhester/lintr/blob/630cc228c62e35ea59c2d5bc3f9812a506a30d5e/R/methods.R#L53-L81

The implementation of `rstudio_source_markers()` could handle empty lints.

**Comment by AshesITR** [comment]
@razz-matazz Do you mind checking out the branch in PR #521 to confirm the bug is fixed for you as welll?
Thanks!

**Comment by razz-matazz** [comment]
i'd love to do so, but never checked out a branch/reviewed a PR... Do you know any guide I can follow?

**Comment by AshesITR** [comment]
You can specify the commit in `remotes::install_github()`.
