### ISSUE TITLE
Investigate the cache with emacs integration

### ISSUE THREAD

**Issue by jimhester** [jimhester/lintr#60]
I was getting some errors until I turned off caching.

**Comment by jimhester** [comment]
This is still broken, needs to be fixed!

**Comment by dankessler** [comment]
I know this is old, but perhaps it's related to [this issue](https://github.com/emacs-ess/ESS/issues/1016)

**Comment by dankessler** [comment]
I think this is the issue described in the (now-closed) #308. I think that editing [this line](https://github.com/jimhester/lintr/blob/89ec4178e6e76d94894cd97b31aa5b6a1a32c39e/R/cache.R#L54) to include `recursive = TRUE` would address the problem where it's unable to create the cache because the `~/.R` directory does not yet exist.

It's a pretty trivial change, but I'd be happy to more thoroughly test it and submit a PR if this approach is welcome.

**Comment by jimhester** [comment]
Sure happy for a PR if you think that solves the issue
