### ISSUE TITLE
Lint errors for function names in packages

### ISSUE THREAD

**Issue by jlegewie** [jimhester/lintr#88]
I am getting the `Variable and function names should be all lowercase` error for function names in packages. `readRDS` doesn't give an error but functions like `spTransform` (`sp` package). The error disappears when I use `sp::spTransform` but that is not really a solution. 

Is that intended?

**Comment by jimhester** [comment]
Lintr only whitelists functions names in the base packages. Personally I always make calls to external packages with `::` so that it is explicit where the function is coming from.  (This is also what Hadley recommends in [R packages](http://r-pkgs.had.co.nz/namespace.html#imports))

You can exclude that line from linting by appending it with `# nolint`.

It may be worth adding functions imported in `NAMESPACE` to the whitelist as well, I will consider it.

**Comment by jlegewie** [comment]
I agree about `::` but I only use it in package development not necessarily in other code. Not sure but I think Hadley is talking about package development. In any case, if that is a rule (and I think it is a good one at least as an option), why not have an error for it. So `spTransform` wouldn't get the `Variable and function names should be all lowercase` error but instead something like `specify namespace`.

In any case, I also to say that it's great to have a linter for R!!!!

**Comment by zachmayer** [comment]
Is there a way to manually add NAMESPACE imports to the whitelist?

**Comment by jimhester** [comment]
Not currently, a nice extension to lintr would be to parse the NAMESPACE file so these names aren't considered, but it is not implemented now.

**Comment by jimhester** [comment]
We now whitelist NAMESPACE imports as well, so this should be mostly fixed https://github.com/jimhester/lintr/blob/ecbd33bdeb8db559245d12494d148351e379e7c2/R/object_name_linters.R#L57
